# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('phone_number_verify_time', models.DateTimeField()),
                ('wx_openid', models.CharField(db_index=True, max_length=20)),
                ('wx_openid_verify_time', models.DateTimeField()),
                ('wx_subscribed', models.BooleanField(default=False)),
                ('qq_openid', models.CharField(db_index=True, max_length=20)),
                ('qq_openid_verify_time', models.DateTimeField()),
                ('weibo_openid', models.CharField(db_index=True, max_length=20)),
                ('weibo_openid_verify_time', models.DateTimeField()),
                ('email', models.CharField(db_index=True, max_length=40)),
                ('email_verify_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_bind',
            },
        ),
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('job_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_collection',
            },
        ),
        migrations.CreateModel(
            name='MyInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('job_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_interview',
            },
        ),
        migrations.CreateModel(
            name='MyRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('job_id', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'my_recommend',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=36)),
                ('nick', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('portrait', models.CharField(max_length=20)),
                ('real_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('vip', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('education', models.CharField(max_length=40)),
                ('nation', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=3)),
                ('birthday', models.DateField()),
                ('certificate_no', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile_ext',
            },
        ),
    ]
