# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160814_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='', max_length=150),
        ),
    ]
