# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_openid', models.CharField(db_index=True, max_length=36)),
                ('wx_subscribed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'wx_subscribe',
            },
        ),
        migrations.RemoveField(
            model_name='bind',
            name='wx_subscribed',
        ),
    ]
