# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160824_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileext',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profileext',
            name='nation',
        ),
        migrations.RemoveField(
            model_name='profileext',
            name='province',
        ),
        migrations.RemoveField(
            model_name='profileext',
            name='street',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='nation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(default='', max_length=10),
        ),
    ]
