# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160827_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(default='', max_length=20),
        ),
    ]
