# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160828_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrecommend',
            name='audio_for_qian',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='myrecommend',
            name='audio_for_zhu',
            field=models.CharField(default='', max_length=32),
        ),
    ]
