# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160831_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecommend',
            name='audio_for_qlm',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='myrecommend',
            name='audio_for_zg',
            field=models.CharField(default='', max_length=80),
        ),
    ]
