# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20160901_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrecommend',
            name='uuid',
            field=models.CharField(db_index=True, default='', max_length=36),
        ),
    ]
