# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_myrecommendmerg_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pub_valid_job_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
