# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile_pub_valid_job_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycollection',
            name='last_share_uuid',
            field=models.CharField(db_index=True, default='00000000000000000000000000000000', max_length=36),
        ),
        migrations.AddField(
            model_name='myinterview',
            name='last_share_uuid',
            field=models.CharField(db_index=True, default='00000000000000000000000000000000', max_length=36),
        ),
        migrations.AddField(
            model_name='myrecommend',
            name='last_share_uuid',
            field=models.CharField(db_index=True, default='00000000000000000000000000000000', max_length=36),
        ),
    ]
