# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20160818_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='piclist',
            field=models.CharField(max_length=256),
        ),
    ]
