# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20160820_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=36),
        ),
    ]
