# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_auto_20160831_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='job',
        ),
        migrations.RemoveField(
            model_name='share',
            name='sound_record_to_hr',
        ),
        migrations.RemoveField(
            model_name='share',
            name='sound_record_to_object',
        ),
        migrations.AddField(
            model_name='share',
            name='recommend_id',
            field=models.IntegerField(default=0),
        ),
    ]
