# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_auto_20160903_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='beinterested',
            name='be_interested_uuid',
            field=models.CharField(db_index=True, default='00000000000000000000000000000000', max_length=36),
        ),
    ]
