# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0014_auto_20160906_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergemsg',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
