# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_auto_20160906_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='last_share_id',
            new_name='last_share_uuid',
        ),
    ]
