# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_auto_20160907_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='job_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
