# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_auto_20160907_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='last_share_uuid',
            field=models.CharField(max_length=36),
        ),
    ]
