# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0019_auto_20160907_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beinterested',
            old_name='share_uuid',
            new_name='last_share_uuid',
        ),
    ]
